# Generated by Django 5.2 on 2025-09-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID de pago de Mercado Pago', max_length=100, null=True),
        ),
    ]
