# Generated by Django 5.2 on 2025-10-19 15:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_description_category_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('logged_users_visits', models.PositiveIntegerField(default=0)),
                ('anonymous_visits', models.PositiveIntegerField(default=0)),
                ('mobile_visits', models.PositiveIntegerField(default=0)),
                ('desktop_visits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Resumen de Visitas',
                'verbose_name_plural': 'Resúmenes de Visitas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('page_url', models.URLField()),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
