# Generated by Django 5.2 on 2025-11-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='converted_to_order',
            field=models.BooleanField(default=False, help_text='Indica si esta reserva se convirtió en un pedido pagado'),
        ),
    ]
