# Generated by Django 5.2 on 2025-09-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_shippingaddress_shipping_address2_and_country'),
        ('payment', '0005_order_date_shipped'),
    ]

    operations = [
    ]
