# Generated by Django 5.2 on 2025-09-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_merge_20250905_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
