# Generated by Django 5.2 on 2025-11-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_order_amount_paid_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Artículo del Pedido', 'verbose_name_plural': 'Artículos del Pedido'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Dirección de Envío', 'verbose_name_plural': 'Direcciones de Envío'},
        ),
    ]
