# Generated by Django 5.2 on 2025-11-10 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_order_options_alter_orderitem_options_and_more'),
        ('store', '0011_reservation_converted_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Reserva que originó este pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.reservation'),
        ),
    ]
