# Generated by Django 5.2 on 2025-11-10 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_order_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('oca', 'OCA'), ('andreani', 'Andreani'), ('correo_argentino', 'Correo Argentino')], max_length=50, unique=True, verbose_name='Método de Envío')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Base')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo por KG')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Envío gratis desde')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('estimated_days', models.CharField(help_text='Ej: 3-5 días hábiles', max_length=50, verbose_name='Días estimados')),
            ],
            options={
                'verbose_name': 'Método de Envío',
                'verbose_name_plural': 'Métodos de Envío',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_with_shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total con Envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.shippingmethod', verbose_name='Método de Envío'),
        ),
    ]
